### PR TITLE
[Fix] add missing icon

### PR DESCRIPTION
**Pull request by David-Henner**
- Added missing info icon to `Images.xcasset`

### CODE REVIEW

**Comment by billypchan** [comment]
Should we add the vector icon in WireStyleKit?

**Comment by David-Henner** [comment]
> Should we add the vector icon in WireStyleKit?

I don't know? How should I do that ?

**Comment by typfel** [comment]
We already have this icon in WireStyleKit, it's called `imageOfLogo()`

**Comment by typfel** [comment]
> > Should we add the vector icon in WireStyleKit?
> 
> I don't know? How should I do that ?

We would need the image in a vector format, then we can add it to our paint code file.

**Comment by David-Henner** [comment]
Closing this PR because the icon already exist in WireStyleKit

**Pull request closed without merging**
